### ISSUE TITLE
Proposal to change JSON structure for preset themes

### ISSUE THREAD

**Issue by johngruen** [mozilla/ThemesRFun#113]
I noticed that the file structure for preset themes is causing a bit of a hiccup in our UI where an extra picker element is being rendered. (hint: look under the toolbar color editor)

![image](https://user-images.githubusercontent.com/3323249/37013385-3e076fcc-20bf-11e8-918f-4653589ad363.png)

Looks like this is happening b/c the new `title` prop is being passed into the `ThemeColorsEditor` as part of the colors object. Easy to see how we're doing this since in that component we use `theme` to mean `colors` in the props declaration on line 21.

So I'd like to propose a few things here: 

1. Let's make the flat files storing themes a bit less flat and use the structure outlined below.
2. As a subsidiary, lets do a quick audit of code to make sure we're using variable declarations consistently so that we don't use the word `colors` when we really mean `themes` (ie: `colors` should be a subsidary of a `theme` along with a `title` and `images`)

FWIW, I've been saving themes I've collected from our visual designers for the past few days, made a big [json](https://gist.github.com/johngruen/df2e5baf44fefcc29b2465b2079c8175) file of all of them from react state. I'll create separate files for each of these once we make a decision here.
```
{
  "title": "001",
  "colors": {
    "toolbar": {
      "h": 187,
      "s": 77,
      "l": 53,
      "a": 100
    },
    "toolbar_text": {
      "h": 213,
      "s": 43,
      "l": 89
    },
    "accentcolor": {
      "h": 187,
      "s": 77,
      "l": 53
    },
    "textcolor": {
      "h": 187,
      "s": 0,
      "l": 33
    },
    "toolbar_field": {
      "h": 211,
      "s": 0,
      "l": 100,
      "a": 53.33333206176758
    },
    "toolbar_field_text": {
      "h": 317,
      "s": 100,
      "l": 64
    }
  },
  "images": {
    "headerURL": "./bg-0.png"
  }
}

```

**Comment by johngruen** [comment]
Oh, i just noticed #112 which solves the immediate issue. Still seems worth considering.

**Comment by johngruen** [comment]
Also, makes more room for doing stuff with images in preset/saved themes

**Comment by pdehaan** [comment]
Looking at @johngruen's big JSON blob, it also has a `modified` key. Not sure if that'd be useful, so we could sort themes by "freshness". Or if we want an `author` field, so we can at least credit the author of the excellent **Hotdog Stand 🌭** theme.

```js
{
  "1519763971760-971": {
    "theme": {
      "colors": {
        "toolbar": {...},
        "toolbar_text": {...},
        "accentcolor": {...},
        "textcolor": {...},
        "toolbar_field": {...},
        "toolbar_field_text": {...}
      },
      "images": {...}
    },
    "modified": 1519763971760
  },
```

**Comment by pdehaan** [comment]
Similarly, if we want some Boolean `isFeatured` field, if we want to randomly highlight some theme[s] of the week.

**Comment by lmorchard** [comment]
> Looking at @johngruen's big JSON blob, it also has a modified key. 

That blob is straight from the saved themes store in Redux. Those are currently sorted in order of modified date. Will probably leave that out of the schema for now, but the general tweak to the structure gives us room to add properties as they look useful to add
