### ISSUE TITLE
UI issues with the theme preview

### ISSUE THREAD

**Issue by johngruen** [mozilla/ThemesRFun#114]
Would prefer apply be the primary action here. Also i think the colors or css are a little off for this version of the browser preview:

![image](https://user-images.githubusercontent.com/3323249/37013948-e790399a-20c2-11e8-9494-95c83136684b.png)

here's the little version:
![image](https://user-images.githubusercontent.com/3323249/37013958-f52ef398-20c2-11e8-8674-ec726814e95d.png)

**Comment by lmorchard** [comment]
Yeah, this preview definitely needs help. [I just sort of fudged a medium size in the dialog PR](https://github.com/mozilla/ThemesRFun/pull/59#issuecomment-364591044)
