### ISSUE TITLE
TRF should indicate that it is a Test Pilot experiment and link back to Test Pilot

### ISSUE THREAD

**Issue by johngruen** [mozilla/ThemesRFun#17]
Similar to send.firefox.com 

@youwenliang

**Comment by lmorchard** [comment]
I think we've got this one done, at least insofar as we mention Test Pilot and link back
![capture](https://user-images.githubusercontent.com/21687/36743302-f3ac10a6-1bb7-11e8-8eef-9a745cd8832b.PNG)
