### ISSUE TITLE
Finalize TRF Icon

### ISSUE THREAD

**Issue by johngruen** [mozilla/ThemesRFun#18]
We need an add-on icon at both 32 x 32px SVG and a 192 x 192 white PNG (for the Test Pilot Site)

**Comment by lmorchard** [comment]
FWIW, from [acceptance.md](https://github.com/mozilla/ThemesRFun/blob/master/docs/acceptance.md):
> - [ ] The browserAction should be a single color SVG icon that accepts a value of `fill=context-fill`

**Comment by youwenliang** [comment]
Here's the Themer Icon measurement & assets:
https://mozilla.github.io/testpilot-assets/ThemesRFun/01_Measurements/App_icon/
Icons: https://github.com/mozilla/testpilot-assets/tree/master/ThemesRFun/01_Measurements/App_icon/assets
