### ISSUE TITLE
Add the capability to select from pre-determined themes

### ISSUE THREAD

**Issue by johngruen** [mozilla/ThemesRFun#24]
As a user, i would like to select from complete example themes. 

This feature is laid out in the spec as 'Popular' themes, but should actually just be a set of complete theme declarations we provide.

This page shows the picker UI: https://mozilla.github.io/testpilot-assets/ThemesRFun/01_Measurements/ThemesRFun/#artboard5

This page shows the hover state: https://mozilla.github.io/testpilot-assets/ThemesRFun/01_Measurements/ThemesRFun/#artboard4

This page shows the selected state: https://mozilla.github.io/testpilot-assets/ThemesRFun/01_Measurements/ThemesRFun/#artboard3

**Comment by apoorvaagupta** [comment]
Hello, @johngruen Can I work on this issue under your mentorship?!

**Comment by johngruen** [comment]
Hey @apoorvaagupta I am actually already working on this one, though i didn't assign myself just yet. The overall UX for for this project are still in progress (at least for the next few weeks) and I'm not sure we're quite ready for contributions since the overall project is subject to change. 

For the moment, I'd recommend looking at some of our other experiments, Screenshots or Test Pilot itself for the best places to contribute! Check back in a week or two and we should have our issues in a better overall state!

**Comment by apoorvaagupta** [comment]
Thanks a lot @johngruen !! I will check other repositories to contribute :)
