### ISSUE TITLE
Add theme approval step if existing user receives theme link

### ISSUE THREAD

**Issue by johngruen** [mozilla/ThemesRFun#27]
If an installed user receives a new theme link, they should be prompted to accept it before their browser's ui gets updated.

Spec here:
https://mozilla.github.io/testpilot-assets/ThemesRFun/01_Measurements/ThemesRFun/

**Comment by lmorchard** [comment]
One wrinkle, if only as a note to myself:
>  It should propagate editor changes up to the browser chrome instantly.
That is, *except* for the initial load with a shared theme link. Should figure out if the easiest way to do that is to add another URL parameter that only gets included on the link share field. But, that wouldn't apply to the URL bar, which is another place that the theme could be shared from.

Maybe just needs to ask permission on initial page startup when a ?theme param is present?

**Comment by johngruen** [comment]
@lmorchard edge case would be not to do it if `themeParam === currentTheme`
