### ISSUE TITLE
Add link to feedback survey

### ISSUE THREAD

**Issue by johngruen** [mozilla/ThemesRFun#29]
Survey link should only appear when the user has TRF installed
Survey link should have the following params:

`ver=${addon-ver} and ref=app`

**Comment by johngruen** [comment]
@youwenliang we don't have ux or assets for this...please provide

**Comment by youwenliang** [comment]
Here's the button:
https://mozilla.github.io/testpilot-assets/ThemesRFun/01_Measurements/ThemeRFun_feedback/
