### ISSUE TITLE
The TRF theme should persist when a user peels off a new window

### ISSUE THREAD

**Issue by johngruen** [mozilla/ThemesRFun#35]
If i pull off a tab into a new window I lose  my TRF theme in the new window. 

Maybe this is a limitation of the API, but it'd be good to know if this behavior is preventable.

**Comment by lmorchard** [comment]
I can reproduce this with dragging a tab off and also just with creating a new window. I don't remember that happening before - looks like maybe an upstream bug. But we might be able to re-apply the current theme in the extension whenever a new window is created as a band-aid
