### ISSUE TITLE
Use cross-env for Windows goodness?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/ThemesRFun#4]
Not sure if we need to use something like [**cross-env**](http://npm.im/cross-env) for cross-OS greatness when passing ENV vars via the CLI. Some potential edges are:

```sh
$ cat package.json | jq '. | {scripts}' | grep "="
```

1.    `"server": "NODE_ENV=development webpack-dev-server --config webpack.web.js",`

1.   ` "watch:web": "NODE_ENV=development webpack --watch --progress --colors --config webpack.web.js",`

1.   `"watch:extension": "NODE_ENV=development webpack --watch --progress --colors --config webpack.extension.js",`

1.    `"build:web": "NODE_ENV=production webpack -p --config webpack.web.js",`

1.    `"build:extension": "NODE_ENV=production webpack -p --config webpack.extension.js",`

1.    ~~`"package": "npm run clean:extension && npm run build:extension && web-ext build --overwrite-dest --source-dir=build/extension && mv web-ext-artifacts/*.zip ./addon.xpi",`~~

1.    ~~`"sign": "npm run clean:extension && npm run build:extension && web-ext sign --source-dir=build/extension && mv web-ext-artifacts/*.xpi ./addon.xpi",`~~

1.    ~~`"run": "npm run build:extension && web-ext run --source-dir=build/extension",`~~

1.    `"release:dev": "ADDON_URL='https://lmorchard.github.io/ThemesRFun/addon.xpi' SITE_URL='https://lmorchard.github.io/ThemesRFun/' npm run release:base"`

**Comment by lmorchard** [comment]
Yeah, I kind of neglected this. I'm actually on Windows. But, I do everything from the WSL bash shell and not powershell

**Comment by lmorchard** [comment]
Un-assigning myself for now so someone else could pick this up if I don't soon

**Comment by Shruti9520** [comment]
@pdehaan @lmorchard Hi, I want to participate in Outreachy current round. Can I work on this issue? :)
Also, If this project already has many potential participants, please let me know. :-)

Thanks!

**Comment by lmorchard** [comment]
@Shruti9520 Hi there, thanks for stopping by! This issue is already closed, so you might have better luck taking a look at one of our other issues labelled "[good first issue](https://github.com/mozilla/Themer/labels/good%20first%20issue)"
