### ISSUE TITLE
Implement GA metrics pings

### ISSUE THREAD

**Issue by lmorchard** [mozilla/ThemesRFun#46]
From [acceptance criteria](https://github.com/mozilla/ThemesRFun/blob/master/docs/acceptance.md):

> - [ ] It should ping GA for all pings described in the [experiment metrics doc](./metrics.md).
> - [ ] It should respect DNT.

**Comment by lmorchard** [comment]
Metrics spec pending in #11

**Comment by lmorchard** [comment]
Do we have a tracking ID for GA?

**Comment by chuckharmston** [comment]
CC @wresuolc for that.

**Comment by wresuolc** [comment]
I'm waiting to get one until we have a final name / domain.  @johngruen
