### ISSUE TITLE
Color chips resize slightly when selecting item

### ISSUE THREAD

**Issue by pdehaan** [mozilla/ThemesRFun#58]
I made a pretty rad [rainbow theme](https://mozilla.github.io/ThemesRFun/?theme=XQAAAAIJAQAAAAAAAABBKYkm0ypxtqu9mB2KK4d4ccIgevwats_sOw9RE2e7oEmWHhMAwySPjd9PWLIRa3i2_IhUrLinugIGwsoHSMQuNXKNe1-IgpFgRFbLo1UG2TF55MYKTtoclNxtrMJBetGlpKbwobZcLVIFPkwaOkSdavp8b6ppcZlVRUNrXgQQ1Cx3FMM3YZAmug4ll-C1byd2tikv6wnjhFt1CFa0B4re5ZesBEdgLxIZxFgnGo5R9OfmbEJpfgM___P2OWw) but noticed that when I select an item to customize, the text grow comically large (FF Nightly), causing the text to wrap and sometimes the circular color chip will squish (see Yellow, Green, Blue, and Purple chips).

![themesrnifty](https://user-images.githubusercontent.com/557895/36046884-4ea07236-0d8f-11e8-85bc-b0879e161532.gif)

**Comment by pdehaan** [comment]
Also worth noting, is that my browser is a 15" rMBP on an external 24" Dell monitor at 50% width (around 959px wide):

![themesrneat](https://user-images.githubusercontent.com/557895/36047246-539809d8-0d90-11e8-9270-0330372945cc.png)

**Comment by lmorchard** [comment]
I think [the text size change is intentional](https://mozilla.github.io/testpilot-assets/ThemesRFun/01_Measurements/ThemesRFun/#artboard6), but not a sized change in the color chip

**Comment by pdehaan** [comment]
The text size change may be contributing to the word wrapping which may affect the chip size, but that wouldn't explain the apparent slight change on "Toolbar Input Background Color" option, which is already wrapped.

It may be worse for more verbose locales like German which may cause strings to wrap to a third line with a smaller viewport.
