### ISSUE TITLE
Audit dependencies

### ISSUE THREAD

**Issue by pdehaan** [mozilla/ThemesRFun#8]
Just a quick check. I think everything looks OK to my aging eyes, but worth a second look with somebody that has more than 20 minutes of experience with this repo:

```sh
$ npx depcheck

Unused dependencies
* json-url

Unused devDependencies
* babel-core
* babel-loader
* babel-plugin-transform-object-rest-spread
* babel-preset-env
* babel-preset-node8
* babel-preset-react
* clean-webpack-plugin
* css-loader
* eclint
* ejs
* eslint-config-airbnb-base
* eslint-plugin-import
* eslint-plugin-react
* image-webpack-loader
* node-sass
* sass-loader
* style-loader
* svg-url-loader
* url-loader
```

**json-url** felt fishy, but looks like we're manually copying the file from ./node_modules/ into a /vendor/ directory (which is cool).

Babel and ESLint and \*-loader results are always fishy, based on how they are loaded by their respective tools.

So I think maybe the only one that strikes me was **eclint**. I didn't see any errors when running `npx eclint .` locally, so I'm guessing there were no editorconfig errors. Not sure if we want to create some npm task which calls **eclint** or not. We _could_ potentially extend `npm run lint` to run ESLint and eclint (and some Sass linter if we feel under-linted).

blah blah blah

---

```sh
$ npx depcheck --ignores=*-loader,eslint-*,babel-*

Unused dependencies
* json-url

Unused devDependencies
* clean-webpack-plugin
* ejs
* node-sass
```

**Comment by lmorchard** [comment]
Look like sass-loader depends on node-sass, despite what depcheck says. Build fails if I omit it from dependencies. The other two - clean-webpack-plugin and ejs - were used in code that I've since deleted, so they can go for now
