### ISSUE TITLE
Just a sea of question marks

### ISSUE THREAD

**Issue by johngruen** [mozilla/ThemesRFun#95]
Noticed by Sean M...

We may need to add Fira to the site.
![screenshot 2018-02-27 12 13 21](https://user-images.githubusercontent.com/3323249/36746878-46fb2e32-1ba8-11e8-9833-3c41ebca2b76.png)

**Comment by chuckharmston** [comment]
You've triggered the secret Mario level easter egg. Enjoy trying to defeat Bowser.
