### ISSUE TITLE
Copy button and textfield are misaligned on Chrome

### ISSUE THREAD

**Issue by pdehaan** [mozilla/ThemesRFun#98]
Using latest release Chrome on macOS:

![firefox_theme_generator_-_chrome](https://user-images.githubusercontent.com/557895/36749986-48e463b8-1bb1-11e8-928e-b158dc441562.png)

And for reference, here's the [same page/theme](https://mozilla.github.io/ThemesRFun/?theme=XQAAAALAAAAAAAAAAABBKYhm849SCiaxqiaEGccwS-xNVABNDRsV6U7qNgnma-u-65mMzb5P6y-1FTqdUX8g5fRMtB6bgj-boR3uAZCs5-mWSne2yj1qEJO06_tD4BsnHzdfsTu9PN5Uf90RXjB6kGOm-6rZhUMCcMAxcBJcSg0qRS4fCtErHO8PVApPkZwgzvBYFYEz4I36_-GKkAA) in Firefox Nightly:

![firefox_theme_generator_-_nightly](https://user-images.githubusercontent.com/557895/36750043-6518e838-1bb1-11e8-8a3c-f4f9f1d302dc.png)

**Comment by johngruen** [comment]
hey, turns out there's a chrome bug causing this!

https://bugs.chromium.org/p/chromium/issues/detail?id=262679
